# Generated by Django 4.1.1 on 2022-10-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
